### ISSUE TITLE
Add a Armature Selection system

### ISSUE THREAD

**Issue by Yusarina** [teamneoneko/Avatar-Toolkit#20]
Similar to how current cats work we need a system where the user can select which armature there are working on in case there have multiple Armatures, like a drop down box.

This will help with the current issue where you have to manually select the armature to have the options work. 

If this is a good idea, please let me know, I not added the will be added tag yet.

**Comment by 989onan** [comment]
This needs to be done, then when it is made it should be merged to the main branch ASAP and all existing PRs would need to be updated. Because tools like Merge Doubles Safely, and other tools that work with meshes or armatures would need to be updated so they only affect meshes that are underneath the armature

Also as an extra addon to this system, users in cats would complain (though the solution was simple enough) that they would have to unparent meshes from the armature to exclude them from bulk operations.

As part of the selecting armatures, a custom UL class that allows the user to mark meshes under the selected armature to be unaffected would be nice.

 Then a helper function for classes that returns only included meshes when an operator gathers the meshes under the selected armature for the view layer. That way if all operators use the helper function, then the excluded meshes will not be touched no matter what
 
 This will cause issues for things like merge bones, but maybe those methods would get their own helper function that bypasses the exclusion, or perhaps a warning to the user that they have excluded meshes that will break the method (If they will even read the error and use more than 2 braincells that is)

**Comment by 989onan** [comment]
The mesh exclusion would need some stuff for things like exporting, and other things, and would need some further design crafting before it's fully implemented

As a good intermediary before implementing mesh exclusion completely, having a helper function that returns all meshes under the armature and doesn't mutate the results in any way would be a good first start.

**Comment by Yusarina** [comment]
Agreed this needs to be done sooner rather then later. Things will need to be updated.

I also agree that it would be nice to unmark mehses and etc, the helper function should be useful, should be stored in common.py for easy access. As you said having the helper function that return all meses would be a good start. 

Re merging bones, I think the warning should be enough, if the message pops up infront of them and if there press OK without reading then personally I think it's there own fault at that point (But maybe that's just my me being me and I might be using my Linux brain too much there). What do you think?

I personally think we should start simple though then build upon it, get the basics out of the way and build the function up as we go, though that's what we kinda been doing anyway with other functions.

**Comment by 989onan** [comment]
I think you or I should pick this up and do the simple thing of making an armature selector, and then a helper function that just returns the meshes underneath the armature

That way if we want to change the internals of the method that returns the meshes to filter out user designated excluded meshes they can

Then everywhere in the code where we have things like "bpy.context.scene.objects" or "bpy.data.objects" or "context.scene.objects" we can replace it with the helper method for later modification if we want to filter out objects we don't wanna affect

**Comment by Yusarina** [comment]
If I get change later today or tomorrow I try and get this done, I won't assign it just yet though unto I get chance.

**Comment by Yusarina** [comment]
I have started this today: https://github.com/teamneoneko/Avatar-Toolkit/pull/30

**Comment by 989onan** [comment]
this is done, closing
